# This is a basic workflow that is manually triggered

name: Test Deploy
run-name: Deploy ${{github.event.action || github.ref_name}} by @${{ github.actor }}

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # inputs:
    #   stage:
    #     description: 'STAGE'
    #     default: 'prod'
    #     required: true

  # https://kontent.ai/blog/how-to-trigger-github-action-using-webhook-with-no-code
  repository_dispatch:
    types:
      - test
  push: 
    branches: 
      - '!master'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  deploy-sls:
    env:
      BRANCH: ${GITHUB_REF#refs/heads/}

    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Extract Branch
        run: |
             echo "BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
             echo branch = ${{ env.BRANCH }}
             echo ${GITHUB_REF#refs/heads/}
             echo ${{ github.ref }}
             echo ${{ github.ref_name }}
             echo ${{ github.base_ref }}
      
      - run: echo event '${{ toJSON(github.event) }}'

      - name: Extract Branch From Webhook
        if: github.event.action == 'webhook'
        run: echo "BRANCH=${{ github.event.client_payload.branch }}" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v3
        with: 
          ref: ${{ env.BRANCH }}

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Run Script
        run: npm run test-deploy

      - run: echo branch = $BRANCH
    
      # - name: Extract Project Name
      #   run: |
      #        BRANCH="${{ env.BRANCH }}"
      #        echo $BRANCH
      #        PROJECT="PRJ=${BRANCH/-prod}"
      #        echo $PROJECT >> $GITHUB_ENV
      #        echo ${{ env.PROJECT }}

      
