# This is a basic workflow that is manually triggered

name: Test Deploy
run-name: Deploy ${{github.event.action || github.ref_name}} by @${{ github.actor }}

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # inputs:
    #   stage:
    #     description: 'STAGE'
    #     default: 'prod'
    #     required: true

  # https://kontent.ai/blog/how-to-trigger-github-action-using-webhook-with-no-code
  repository_dispatch:
    types:
      - webhook

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  deploy-sls:
    env:
      BRANCH: ${GITHUB_REF#refs/heads/}

    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        if: github.event.action == 'webhook'
        uses: actions/checkout@v3
        with: 
          ref: ${{ github.event.client_payload.branch }}

      - name: Extract Branch
        run: |
             echo "BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
             echo branch = ${{ env.BRANCH }}
             echo ${GITHUB_REF#refs/heads/}
             echo ${{ github.ref }}
             echo ${{ github.head_ref }}
             echo ${{ github.base_ref }}

      - name: Extract Branch From Webhook
        if: github.event.action == 'webhook'
        run: echo "BRANCH=${{ github.event.client_payload.branch }}" >> $GITHUB_ENV
    
      # - name: Extract Project Name
      #   run: |
      #        BRANCH="${{ env.BRANCH }}"
      #        echo $BRANCH
      #        PROJECT="PRJ=${BRANCH/-prod}"
      #        echo $PROJECT >> $GITHUB_ENV
      #        echo ${{ env.PROJECT }}

      
